version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: springboot_postgres
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: tmdbuser123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "6070:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
